bases:
- ../base

resources:
- namespace.yaml
- postgres.yaml
- postgres-parodos.yaml
- backstage.yaml

patchesStrategicMerge:
- parodos-patch.yaml

configMapGenerator:
- name: app-config
  namespace: backstage
  files:
  - app-config.yaml

secretGenerator:
- name: postgres-secrets
  namespace: backstage
  literals:
  - POSTGRES_USER=admin
  - POSTGRES_PASSWORD=admin
  - PGDATA=/var/lib/postgresql/data/mydata

- name: postgres-secrets-default
  namespace: default
  literals:
  - POSTGRES_USER=parodos
  - POSTGRES_PASSWORD=parodos
  - POSTGRES_DB=parodos
  - PGDATA=/var/lib/postgresql/data/mydata
