bases:
- ../base

resources:
- postgres-parodos.yaml
- backstage.yaml

patchesStrategicMerge:
- parodos-patch.yaml

configMapGenerator:
- name: app-config
  files:
  - app-config.yaml

secretGenerator:
- name: postgres-secrets
  literals:
  - POSTGRES_USER=parodos
  - POSTGRES_PASSWORD=parodos
  - POSTGRES_DB=parodos
  - PGDATA=/var/lib/postgresql/data/mydata
