apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-service
spec:
  template:
    spec:
      containers:
      - name: workflow-service
        env:
        - name: "SPRING_PROFILES_ACTIVE"
          value: "local"
