apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-service
spec:
  template:
    spec:
      containers:
      - name: workflow-service
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: keys-volume
          mountPath: "/opt/keys"
      volumes:
      - name: keys-volume
        configMap:
          name: move2kube-keys
          defaultMode: 0777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-service-config
data:
  SPRING_PROFILES_ACTIVE: "local"
  NOTIFICATION_SERVER_URL: "http://notification-service.default.svc.cluster.local:8080"
  M2K_URL: "http://move2kube.move2kube.svc.cluster.local:8080/api/v1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  SPRING_PROFILES_ACTIVE: "local"
