---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: parados-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: workflow-service
            port:
              number: 8080
