bases:
- ../base
resources:
- ingress.yaml
- ldap.yaml
- postgres.yaml

patchesStrategicMerge:
- parodos-patch.yaml

images:
- name: quay.io/parodos-dev/workflow-service:main
  newTag: test

- name: quay.io/parodos-dev/notification-service:main
  newTag: test

configMapGenerator:
- name: ldif-config
  files:
  - test-server.ldif
