apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-service-config
data:
  POSTGRES_PASSWORD: parodos
  POSTGRES_DB: parodos
  POSTGRES_USER: parodos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  selector:
    matchLabels:
      app: postgres-service
  template:
    metadata:
      labels:
        app: postgres-service
    spec:
      containers:
      - name: postgres-service
        image: docker.io/postgres:15.2
        ports:
          - containerPort: 5432
            name: insecure
        envFrom:
          - configMapRef:
              name: postgres-service-config
        readinessProbe:
          exec:
            command: ["pg_isready"]
          initialDelaySeconds: 15
          timeoutSeconds: 2
        livenessProbe:
          exec:
            command: ["pg_isready"]
          initialDelaySeconds: 15
          timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres-service
  name: postgres
spec:
  selector:
    app: postgres-service
  ports:
    - protocol: TCP
      name: insecure
      port: 5432
      targetPort: 5432
