name: Prepare new version

on:
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check content
        run: |
          ls -l .
          git log -1

