---
name: Tests
on:
  push:
    branches:
      - main
      - 'releases/**'
      - 'GHActions'

  pull_request:
    branches:
      - '**'


permissions:
  pull-requests: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Maven Build
        run: mvn clean package

      - name: Maven Validate
        run: mvn validate

      - name: Maven Test
        run: |
          mvn test --file ./pom.xml
          mvn jacoco:report-aggregate

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@main
        with:
          paths: ./coverage/target/site/jacoco-aggregate/jacoco.xml
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          token: ${{ secrets.GITHUB_TOKEN }}
