---
name: Tests
on:
  push:
    branches:
      - main
      - 'releases/**'
      - 'GHActions'

  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Maven Build
        run: mvn clean package

      - name: Maven Validate
        run: mvn validate

      - name: Maven Test
        run: |
          mvn test --file ./pom.xml
          mvn jacoco:report-aggregate
          ls ./coverage/target/site/jacoco-aggregate/ -la
          ls ${{ github.workspace }}/ -lah
          ls ${{ github.workspace }}/coverage/target/site/jacoco-aggregate/ -lah
          find ${{ github.workspace }} | grep reports

      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v4.8
        with:
          coverage_results_path: ${{ github.workspace }}/coverage/target/site/jacoco-aggregate/jacoco.xml
          coverage_report_name: Coverage
          coverage_report_title: Coverage
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 60
          fail_below_threshold: false
          publish_only_summary: false

      # Publish Coverage Job Summary  # Optional
      - name: Add Coverage Job Summary
        run: echo "${{ steps.jacoco_reporter.outputs.coverageSummary }}" >> $GITHUB_STEP_SUMMARY
